version: '2.1'

services:
  unbound-mailcow:
    image: mailcow/unbound:1.19
    environment:
      - TZ=UTC
    volumes:
      - ./data/hooks/unbound:/hooks:Z
      - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.254
        aliases:
          - unbound

  mysql-mailcow:
    image: mariadb:10.11
    depends_on:
      - unbound-mailcow
    stop_grace_period: 45s
    volumes:
      - mysql-vol-1:/var/lib/mysql/:Z
      - ./data/conf/mysql/:/etc/mysql/conf.d/:ro,Z
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=mailcow
      - MYSQL_USER=mailcow
      - MYSQL_PASSWORD=changeme
    restart: always
    networks:
      mailcow-network:
        aliases:
          - mysql

  redis-mailcow:
    image: redis:7-alpine
    volumes:
      - redis-vol-1:/data/:Z
    restart: always
    environment:
      - TZ=UTC
    networks:
      mailcow-network:
        aliases:
          - redis

  clamd-mailcow:
    image: mailcow/clamd:1.65
    restart: always
    environment:
      - TZ=UTC
    volumes:
      - ./data/conf/clamav/:/etc/clamav/:Z
    networks:
      mailcow-network:
        aliases:
          - clamd

  rspamd-mailcow:
    image: mailcow/rspamd:1.96
    stop_grace_period: 30s
    depends_on:
      - nginx-mailcow
    environment:
      - TZ=UTC
    volumes:
      - ./data/hooks/rspamd:/hooks:Z
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom:z
      - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d:Z
      - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d:Z
      - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d:Z
      - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro,Z
      - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local:Z
      - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override:Z
      - rspamd-vol-1:/var/lib/rspamd:Z
    restart: always
    networks:
      mailcow-network:
        aliases:
          - rspamd

  nginx-mailcow:
    depends_on:
      - sogo-mailcow
      - php-fpm-mailcow
    image: nginx:mainline-alpine
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active &&
      envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active &&
      envsubst < /etc/nginx/conf.d/templates/sogo.template > /etc/nginx/conf.d/sogo.active &&
      . /etc/nginx/conf.d/templates/server_name.template.sh > /etc/nginx/conf.d/server_name.active &&
      . /etc/nginx/conf.d/templates/sites.template.sh > /etc/nginx/conf.d/sites.active &&
      . /etc/nginx/conf.d/templates/sogo_eas.template.sh > /etc/nginx/conf.d/sogo_eas.active &&
      nginx -qt &&
      until ping phpfpm -c1 > /dev/null; do sleep 1; done &&
      until ping sogo -c1 > /dev/null; do sleep 1; done &&
      until ping redis -c1 > /dev/null; do sleep 1; done &&
      until ping rspamd -c1 > /dev/null; do sleep 1; done &&
      exec nginx -g 'daemon off;'"
    environment:
      - HTTPS_PORT=8443
      - HTTP_PORT=8080
      - MAILCOW_HOSTNAME=mail.reliatrack.org
      - TZ=UTC
    volumes:
      - ./data/web:/web:ro,z
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro,z
      - ./data/assets/ssl/:/etc/ssl/mail/:ro,z
      - ./data/conf/nginx/:/etc/nginx/conf.d/:z
      - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro,z
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: always
    networks:
      mailcow-network:
        aliases:
          - nginx

  sogo-mailcow:
    image: mailcow/sogo:1.119
    environment:
      - DBNAME=mailcow
      - DBUSER=mailcow
      - DBPASS=changeme
      - TZ=UTC
      - MAILCOW_HOSTNAME=mail.reliatrack.org
    volumes:
      - ./data/conf/sogo/:/etc/sogo/:z
      - ./data/web/inc/init_db.inc.php:/init_db.inc.php:z
      - ./data/conf/sogo/custom-favicon.ico:/usr/lib/GNUstep/SOGo/WebServerResources/img/sogo.ico:z
      - ./data/conf/sogo/custom-theme.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/theme.js:z
      - ./data/conf/sogo/custom-sogo.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/custom-sogo.js:z
      - sogo-web-vol-1:/sogo_web
    restart: always
    networks:
      mailcow-network:
        aliases:
          - sogo

  php-fpm-mailcow:
    image: mailcow/phpfpm:1.88
    command: "php-fpm -d date.timezone=UTC -d expose_php=0"
    depends_on:
      - redis-mailcow
    volumes:
      - ./data/hooks/phpfpm:/hooks:Z
      - ./data/web:/web:z
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro,z
      - ./data/conf/rspamd/custom/:/rspamd_custom_maps:z
      - ./data/conf/phpfpm/sogo-sso/:/etc/sogo-sso/:z
      - ./data/conf/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf:Z
      - ./data/conf/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:Z
      - ./data/conf/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini:Z
      - ./data/conf/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini:Z
      - ./data/conf/dovecot/global_sieve_before:/global_sieve/before:z
      - ./data/conf/dovecot/global_sieve_after:/global_sieve/after:z
      - ./data/assets/templates:/tpls:z
      - ./data/conf/nginx/:/etc/nginx/conf.d/:z
    environment:
      - REDIS_SLAVEOF_IP=
      - REDIS_SLAVEOF_PORT=
      - LOG_LINES=9999
      - TZ=UTC
      - MAILCOW_HOSTNAME=mail.reliatrack.org
      - DBNAME=mailcow
      - DBUSER=mailcow
      - DBPASS=changeme
      - MAILCOW_PASS_SCHEME=BLF-CRYPT
    restart: always
    networks:
      mailcow-network:
        aliases:
          - phpfpm

  postfix-mailcow:
    image: mailcow/postfix:1.73
    volumes:
      - ./data/hooks/postfix:/hooks:Z
      - ./data/conf/postfix:/opt/postfix/conf:z
      - ./data/assets/ssl:/etc/ssl/mail/:ro,Z
      - postfix-vol-1:/var/spool/postfix:z
      - crypt-vol-1:/var/lib/zeyple:z
    environment:
      - LOG_LINES=9999
      - TZ=UTC
      - MAILCOW_HOSTNAME=mail.reliatrack.org
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "2525:25"
      - "2587:587"
    restart: always
    networks:
      mailcow-network:
        aliases:
          - postfix

  dovecot-mailcow:
    image: mailcow/dovecot:1.24
    depends_on:
      - mysql-mailcow
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./data/hooks/dovecot:/hooks:Z
      - ./data/conf/dovecot:/etc/dovecot:z
      - ./data/assets/ssl:/etc/ssl/mail/:ro,Z
      - ./data/conf/sogo/:/etc/sogo/:z
      - vmail-vol-1:/var/vmail:Z
      - vmail-index-vol-1:/var/vmail_index:Z
      - crypt-vol-1:/mail_crypt/:z
    environment:
      - LOG_LINES=9999
      - MAILCOW_HOSTNAME=mail.reliatrack.org
      - TZ=UTC
    ports:
      - "2993:993"
      - "2995:995"
      - "2143:143"
      - "4190:4190"
    restart: always
    networks:
      mailcow-network:
        aliases:
          - dovecot

volumes:
  vmail-vol-1:
  vmail-index-vol-1:
  mysql-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  postfix-vol-1:
  crypt-vol-1:
  sogo-web-vol-1:

networks:
  mailcow-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
